CREATE TABLE usuarios (
  id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
  nombre VARCHAR(100),
  email VARCHAR(100) UNIQUE,
  contrasena VARCHAR(255),
  rol ENUM('admin', 'usuario'),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
